// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SWIMS.Models;

public partial class SwimsDb_moreContext : DbContext
{
    public SwimsDb_moreContext(DbContextOptions<SwimsDb_moreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SW_beneficiary> SW_beneficiaries { get; set; }

    public virtual DbSet<SW_city> SW_cities { get; set; }

    public virtual DbSet<SW_financial_institution> SW_financial_institutions { get; set; }

    public virtual DbSet<SW_form> SW_forms { get; set; }

    public virtual DbSet<SW_formProcess> SW_formProcesses { get; set; }

    public virtual DbSet<SW_formReport> SW_formReports { get; set; }

    public virtual DbSet<SW_formTableData_Type> SW_formTableData_Types { get; set; }

    public virtual DbSet<SW_formTableDatum> SW_formTableData { get; set; }

    public virtual DbSet<SW_formTableName> SW_formTableNames { get; set; }

    public virtual DbSet<SW_identity> SW_identities { get; set; }

    public virtual DbSet<SW_organization> SW_organizations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SW_beneficiary>(entity =>
        {
            entity.ToTable("SW_beneficiary");

            entity.Property(e => e.uuid).IsRequired();
        });

        modelBuilder.Entity<SW_city>(entity =>
        {
            entity.ToTable("SW_city");
        });

        modelBuilder.Entity<SW_financial_institution>(entity =>
        {
            entity.ToTable("SW_financial_institution");
        });

        modelBuilder.Entity<SW_form>(entity =>
        {
            entity.HasIndex(e => e.SW_identityId, "IX_FK_SW_identitySW_forms");

            entity.Property(e => e.dateModified).HasColumnType("datetime");
            entity.Property(e => e.name).IsRequired();

            entity.HasOne(d => d.SW_identity).WithMany(p => p.SW_forms)
                .HasForeignKey(d => d.SW_identityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SW_identitySW_forms");
        });

        modelBuilder.Entity<SW_formProcess>(entity =>
        {
            entity.Property(e => e.url).IsRequired();
        });

        modelBuilder.Entity<SW_formReport>(entity =>
        {
            entity.ToTable("SW_formReport");

            entity.HasIndex(e => e.SW_formsId, "IX_FK_SW_formsSW_formReport");

            entity.Property(e => e.url).IsRequired();

            entity.HasOne(d => d.SW_forms).WithMany(p => p.SW_formReports)
                .HasForeignKey(d => d.SW_formsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SW_formsSW_formReport");
        });

        modelBuilder.Entity<SW_formTableData_Type>(entity =>
        {
            entity.HasIndex(e => e.SW_formsId, "IX_FK_SW_formsSW_formTableData_Types");

            entity.HasOne(d => d.SW_forms).WithMany(p => p.SW_formTableData_Types)
                .HasForeignKey(d => d.SW_formsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SW_formsSW_formTableData_Types");
        });

        modelBuilder.Entity<SW_formTableDatum>(entity =>
        {
            entity.HasIndex(e => e.SW_formsId, "IX_FK_SW_formsSW_formTableData");

            entity.HasOne(d => d.SW_forms).WithMany(p => p.SW_formTableData)
                .HasForeignKey(d => d.SW_formsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SW_formsSW_formTableData");
        });

        modelBuilder.Entity<SW_formTableName>(entity =>
        {
            entity.ToTable("SW_formTableName");

            entity.HasIndex(e => e.SW_formsId, "IX_FK_SW_formsSW_formTableName");

            entity.HasOne(d => d.SW_forms).WithMany(p => p.SW_formTableNames)
                .HasForeignKey(d => d.SW_formsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SW_formsSW_formTableName");
        });

        modelBuilder.Entity<SW_identity>(entity =>
        {
            entity.ToTable("SW_identity");

            entity.Property(e => e.name).IsRequired();
        });

        modelBuilder.Entity<SW_organization>(entity =>
        {
            entity.ToTable("SW_organization");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}