// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWIMS.Data.Reports;

#nullable disable

namespace SWIMS.Migrations.Reports
{
    [DbContext(typeof(SwimsReportsDbContext))]
    partial class SwimsReportsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWIMS.Models.Reports.SwReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("ParamCheck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PathOverride")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SW_reports", "rpt");
                });

            modelBuilder.Entity("SWIMS.Models.Reports.SwReportParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ParamDataType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ParamKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ParamValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("SwReportId")
                        .HasColumnType("int");

                    b.Property<int?>("SwSiteIdentityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SwReportId");

                    b.HasIndex("SwSiteIdentityId");

                    b.ToTable("SW_reports_params", "rpt");
                });

            modelBuilder.Entity("SWIMS.Models.SwForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData06")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData07")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData08")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData09")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData100")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData101")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData102")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData103")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData104")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData105")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData106")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData107")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData108")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData109")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData110")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData111")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData112")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData113")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData114")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData115")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData116")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData117")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData118")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData119")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData120")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData121")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData122")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData123")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData124")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData125")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData126")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData127")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData128")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData129")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData130")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData131")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData132")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData133")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData134")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData135")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData136")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData137")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData138")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData139")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData140")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData141")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData142")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData143")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData144")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData145")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData146")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData147")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData148")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData149")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData150")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData151")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData152")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData153")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData154")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData155")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData156")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData157")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData158")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData159")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData160")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData161")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData162")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData163")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData164")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData165")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData166")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData167")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData168")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData169")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData170")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData171")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData172")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData173")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData174")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData175")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData176")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData177")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData178")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData179")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData180")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData181")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData182")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData183")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData184")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData185")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData186")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData187")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData188")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData189")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData190")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData191")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData192")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData193")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData194")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData195")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData196")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData197")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData198")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData199")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData200")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData201")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData202")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData203")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData204")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData205")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData206")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData207")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData208")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData209")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData210")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData211")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData212")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData213")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData214")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData215")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData216")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData217")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData218")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData219")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData220")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData221")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData222")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData223")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData224")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData225")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData226")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData227")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData228")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData229")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData230")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData231")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData232")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData233")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData234")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData235")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData236")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData237")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData238")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData239")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData24")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData240")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData241")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData242")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData243")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData244")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData245")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData246")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData247")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData248")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData249")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData25")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData250")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData26")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData27")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData28")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData29")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData30")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData31")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData33")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData34")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData35")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData36")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData37")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData38")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData39")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData40")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData41")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData42")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData43")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData44")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData45")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData46")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData47")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData48")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData49")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData50")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData51")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData52")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData53")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData54")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData55")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData56")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData57")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData58")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData59")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData60")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData61")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData62")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData63")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData65")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData66")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData67")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData68")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData69")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData70")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData71")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData72")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData73")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData74")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData75")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData76")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData77")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData78")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData79")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData80")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData81")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData82")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData83")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData84")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData85")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData86")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData87")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData88")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData89")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData90")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData91")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData92")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData93")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData94")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData95")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData96")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData97")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData98")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData99")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("IsApproval01")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("IsApproval02")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("IsApproval03")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SwIdentityId")
                        .HasColumnType("int");

                    b.Property<int?>("Uuid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SwIdentityId");

                    b.ToTable("SwForm");
                });

            modelBuilder.Entity("SWIMS.Models.SwFormsTableName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SwFormsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SwFormsId");

                    b.ToTable("SwFormsTableName");
                });

            modelBuilder.Entity("SWIMS.Models.SwSiteIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Media01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Media02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Media03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SwSiteIdentity");
                });

            modelBuilder.Entity("SWIMS.Models.Reports.SwReportParam", b =>
                {
                    b.HasOne("SWIMS.Models.Reports.SwReport", "SwReport")
                        .WithMany("Params")
                        .HasForeignKey("SwReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWIMS.Models.SwSiteIdentity", "SwSiteIdentity")
                        .WithMany()
                        .HasForeignKey("SwSiteIdentityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SwReport");

                    b.Navigation("SwSiteIdentity");
                });

            modelBuilder.Entity("SWIMS.Models.SwForm", b =>
                {
                    b.HasOne("SWIMS.Models.SwSiteIdentity", "SwIdentity")
                        .WithMany("SwForms")
                        .HasForeignKey("SwIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwIdentity");
                });

            modelBuilder.Entity("SWIMS.Models.SwFormsTableName", b =>
                {
                    b.HasOne("SWIMS.Models.SwForm", "SwForms")
                        .WithMany("SwFormsTableNames")
                        .HasForeignKey("SwFormsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwForms");
                });

            modelBuilder.Entity("SWIMS.Models.Reports.SwReport", b =>
                {
                    b.Navigation("Params");
                });

            modelBuilder.Entity("SWIMS.Models.SwForm", b =>
                {
                    b.Navigation("SwFormsTableNames");
                });

            modelBuilder.Entity("SWIMS.Models.SwSiteIdentity", b =>
                {
                    b.Navigation("SwForms");
                });
#pragma warning restore 612, 618
        }
    }
}
