// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.EntityFrameworkCore;
using SWIMS.Models;
namespace SWIMS.Models;

public partial class SW_beneficiary
{
    public int Id { get; set; }

    public string uuid { get; set; }

    public string first_name { get; set; }

    public string middle_name { get; set; }

    public string last_name { get; set; }

    public string dob { get; set; }

    public string gender { get; set; }

    public string martial_status { get; set; }

    public string id_number { get; set; }

    public string telephone_number { get; set; }

    public string status { get; set; }

    public double? approved_amount { get; set; }

    public string name { get; set; }
}
