// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.EntityFrameworkCore;
using SWIMS.Models;

namespace SWIMS.Models;

public partial class SW_city
{
    public int Id { get; set; }

    public string name { get; set; }
}

public static class SW_cityEndpoints
{
    public static void MapSW_cityEndpoints (this IEndpointRouteBuilder routes)
    {
        var group = routes.MapGroup("/api/city").WithTags(nameof(SW_city));

        group.MapGet("/", async (HttpContext http, SwimsDb_moreContext db) =>
        {
            return await db.SW_cities.ToListAsync();
        })
        .WithName("GetAllSW_cities")
        .WithOpenApi();

        group.MapGet("/{id}", async Task<Results<Ok<SW_city>, NotFound>> (int id, SwimsDb_moreContext db) =>
        {
            return await db.SW_cities.AsNoTracking()
                .FirstOrDefaultAsync(model => model.Id == id)
                is SW_city model
                    ? TypedResults.Ok(model)
                    : TypedResults.NotFound();
        })
        .WithName("GetSW_cityById")
        .WithOpenApi();

        group.MapPut("/{id}", async Task<Results<Ok, NotFound>> (HttpContext http, int id, SW_city sW_city, SwimsDb_moreContext db) =>
        {
            var affected = await db.SW_cities
                .Where(model => model.Id == id)
                .ExecuteUpdateAsync(setters => setters
                  .SetProperty(m => m.Id, sW_city.Id)
                  .SetProperty(m => m.name, sW_city.name)
                  );
            return affected == 1 ? TypedResults.Ok() : TypedResults.NotFound();
        })
        .WithName("UpdateSW_city")
        .WithOpenApi();

        group.MapPost("/", async (HttpContext http, SW_city sW_city, SwimsDb_moreContext db) =>
        {
            db.SW_cities.Add(sW_city);
            await db.SaveChangesAsync();
            return TypedResults.Created($"/api/SW_city/{sW_city.Id}",sW_city);
        })
        .WithName("CreateSW_city")
        .WithOpenApi();

        group.MapDelete("/{id}", async Task<Results<Ok, NotFound>> (HttpContext http, int id, SwimsDb_moreContext db) =>
        {
            var affected = await db.SW_cities
                .Where(model => model.Id == id)
                .ExecuteDeleteAsync();
            return affected == 1 ? TypedResults.Ok() : TypedResults.NotFound();
        })
        .WithName("DeleteSW_city")
        .WithOpenApi();
    }
}