// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWIMS.Models;

public partial class SW_formProcess
{
    public int Id { get; set; }

    public string url { get; set; }

    public string name { get; set; }

    public int SW_formsId { get; set; }
}