// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWIMS.Models;

public partial class SW_formTableData_Type
{
    public int Id { get; set; }

    public string type { get; set; }

    public string field { get; set; }

    public int SW_formsId { get; set; }

    public virtual SW_form SW_forms { get; set; }
}