// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SWIMS.Models.Logging;
using System;
using System.Collections.Generic;

namespace SWIMS.Models;

public partial class SW_form
{
    public int Id { get; set; }

    public string uuid { get; set; }

    public string name { get; set; }

    public string desc { get; set; }

    public string form { get; set; }

    public DateTime dateModified { get; set; }

    public int SW_identityId { get; set; }

    public bool? is_linking { get; set; }

    public string image { get; set; }

    public string header { get; set; }

    public int? approvalAmt { get; set; }

    public virtual ICollection<SW_formReport> SW_formReports { get; set; } = new List<SW_formReport>();

    public virtual ICollection<SW_formTableDatum> SW_formTableData { get; set; } = new List<SW_formTableDatum>();

    public virtual ICollection<SW_formTableData_Type> SW_formTableData_Types { get; set; } = new List<SW_formTableData_Type>();

    public virtual ICollection<SW_formTableName> SW_formTableNames { get; set; } = new List<SW_formTableName>();

    public virtual SW_identity SW_identity { get; set; }
}