// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.EntityFrameworkCore;
using SWIMS.Models;

namespace SWIMS.Models;

public partial class SW_organization
{
    public int Id { get; set; }

    public string vendor_id { get; set; }

    public string name { get; set; }

    public string type { get; set; }

    public string active { get; set; }
}
