// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWIMS.Models;

public partial class SwFormsTableName
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int SwFormsId { get; set; }

    public virtual SwForm SwForms { get; set; }
}