// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SWIMS.Models;

public partial class SwimsDb_moreContext : DbContext
{
    public SwimsDb_moreContext(DbContextOptions<SwimsDb_moreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SwForm> SwForms { get; set; }

    public virtual DbSet<SwIdentity> SwIdentities { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SwForm>(entity =>
        {
            entity.ToTable("SW_forms");

            entity.HasIndex(e => e.SwIdentityId, "IX_FK_SW_identitySW_forms");

            entity.Property(e => e.DateModified)
                .HasColumnType("datetime")
                .HasColumnName("dateModified");
            entity.Property(e => e.Desc).HasColumnName("desc");
            entity.Property(e => e.Form).HasColumnName("form");
            entity.Property(e => e.IsApproval01).HasColumnName("isApproval_01");
            entity.Property(e => e.IsApproval02).HasColumnName("isApproval_02");
            entity.Property(e => e.IsApproval03).HasColumnName("isApproval_03");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
            entity.Property(e => e.SwIdentityId).HasColumnName("SW_identityId");
            entity.Property(e => e.Uuid).HasColumnName("uuid");

            entity.HasOne(d => d.SwIdentity).WithMany(p => p.SwForms)
                .HasForeignKey(d => d.SwIdentityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SW_identitySW_forms");
        });

        modelBuilder.Entity<SwIdentity>(entity =>
        {
            entity.ToTable("SW_identity");

            entity.Property(e => e.Desc).HasColumnName("desc");
            entity.Property(e => e.Header).HasColumnName("header");
            entity.Property(e => e.Logo).HasColumnName("logo");
            entity.Property(e => e.Media01).HasColumnName("media_01");
            entity.Property(e => e.Media02).HasColumnName("media_02");
            entity.Property(e => e.Media03).HasColumnName("media_03");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
            entity.Property(e => e.Signature).HasColumnName("signature");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}