// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SWIMS.Models;

public partial class SwimsDb_moreContext : DbContext
{
    public SwimsDb_moreContext(DbContextOptions<SwimsDb_moreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SwForm> SwForms { get; set; }

    public virtual DbSet<SwFormsTableName> SwFormsTableNames { get; set; }

    public virtual DbSet<SwIdentity> SwIdentities { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SwForm>(entity =>
        {
            entity.ToTable("SW_forms");

            entity.HasIndex(e => e.SwIdentityId, "IX_FK_SW_identitySW_forms");

            entity.Property(e => e.DateModified)
                .HasColumnType("datetime")
                .HasColumnName("dateModified");
            entity.Property(e => e.Desc)
                .IsRequired()
                .HasColumnName("desc");
            entity.Property(e => e.Form)
                .IsRequired()
                .HasColumnName("form");
            entity.Property(e => e.FormData01).HasColumnName("formData_01");
            entity.Property(e => e.FormData02).HasColumnName("formData_02");
            entity.Property(e => e.FormData03).HasColumnName("formData_03");
            entity.Property(e => e.FormData04).HasColumnName("formData_04");
            entity.Property(e => e.FormData05).HasColumnName("formData_05");
            entity.Property(e => e.FormData06).HasColumnName("formData_06");
            entity.Property(e => e.FormData07).HasColumnName("formData_07");
            entity.Property(e => e.FormData08).HasColumnName("formData_08");
            entity.Property(e => e.FormData09).HasColumnName("formData_09");
            entity.Property(e => e.FormData10).HasColumnName("formData_10");
            entity.Property(e => e.FormData100).HasColumnName("formData_100");
            entity.Property(e => e.FormData101).HasColumnName("formData_101");
            entity.Property(e => e.FormData102).HasColumnName("formData_102");
            entity.Property(e => e.FormData103).HasColumnName("formData_103");
            entity.Property(e => e.FormData104).HasColumnName("formData_104");
            entity.Property(e => e.FormData105).HasColumnName("formData_105");
            entity.Property(e => e.FormData106).HasColumnName("formData_106");
            entity.Property(e => e.FormData107).HasColumnName("formData_107");
            entity.Property(e => e.FormData108).HasColumnName("formData_108");
            entity.Property(e => e.FormData109).HasColumnName("formData_109");
            entity.Property(e => e.FormData11).HasColumnName("formData_11");
            entity.Property(e => e.FormData110).HasColumnName("formData_110");
            entity.Property(e => e.FormData111).HasColumnName("formData_111");
            entity.Property(e => e.FormData112).HasColumnName("formData_112");
            entity.Property(e => e.FormData113).HasColumnName("formData_113");
            entity.Property(e => e.FormData114).HasColumnName("formData_114");
            entity.Property(e => e.FormData115).HasColumnName("formData_115");
            entity.Property(e => e.FormData116).HasColumnName("formData_116");
            entity.Property(e => e.FormData117).HasColumnName("formData_117");
            entity.Property(e => e.FormData118).HasColumnName("formData_118");
            entity.Property(e => e.FormData119).HasColumnName("formData_119");
            entity.Property(e => e.FormData12).HasColumnName("formData_12");
            entity.Property(e => e.FormData120).HasColumnName("formData_120");
            entity.Property(e => e.FormData121).HasColumnName("formData_121");
            entity.Property(e => e.FormData122).HasColumnName("formData_122");
            entity.Property(e => e.FormData123).HasColumnName("formData_123");
            entity.Property(e => e.FormData124).HasColumnName("formData_124");
            entity.Property(e => e.FormData125).HasColumnName("formData_125");
            entity.Property(e => e.FormData126).HasColumnName("formData_126");
            entity.Property(e => e.FormData127).HasColumnName("formData_127");
            entity.Property(e => e.FormData128).HasColumnName("formData_128");
            entity.Property(e => e.FormData129).HasColumnName("formData_129");
            entity.Property(e => e.FormData13).HasColumnName("formData_13");
            entity.Property(e => e.FormData130).HasColumnName("formData_130");
            entity.Property(e => e.FormData131).HasColumnName("formData_131");
            entity.Property(e => e.FormData132).HasColumnName("formData_132");
            entity.Property(e => e.FormData133).HasColumnName("formData_133");
            entity.Property(e => e.FormData134).HasColumnName("formData_134");
            entity.Property(e => e.FormData135).HasColumnName("formData_135");
            entity.Property(e => e.FormData136).HasColumnName("formData_136");
            entity.Property(e => e.FormData137).HasColumnName("formData_137");
            entity.Property(e => e.FormData138).HasColumnName("formData_138");
            entity.Property(e => e.FormData139).HasColumnName("formData_139");
            entity.Property(e => e.FormData14).HasColumnName("formData_14");
            entity.Property(e => e.FormData140).HasColumnName("formData_140");
            entity.Property(e => e.FormData141).HasColumnName("formData_141");
            entity.Property(e => e.FormData142).HasColumnName("formData_142");
            entity.Property(e => e.FormData143).HasColumnName("formData_143");
            entity.Property(e => e.FormData144).HasColumnName("formData_144");
            entity.Property(e => e.FormData145).HasColumnName("formData_145");
            entity.Property(e => e.FormData146).HasColumnName("formData_146");
            entity.Property(e => e.FormData147).HasColumnName("formData_147");
            entity.Property(e => e.FormData148).HasColumnName("formData_148");
            entity.Property(e => e.FormData149).HasColumnName("formData_149");
            entity.Property(e => e.FormData15).HasColumnName("formData_15");
            entity.Property(e => e.FormData150).HasColumnName("formData_150");
            entity.Property(e => e.FormData151).HasColumnName("formData_151");
            entity.Property(e => e.FormData152).HasColumnName("formData_152");
            entity.Property(e => e.FormData153).HasColumnName("formData_153");
            entity.Property(e => e.FormData154).HasColumnName("formData_154");
            entity.Property(e => e.FormData155).HasColumnName("formData_155");
            entity.Property(e => e.FormData156).HasColumnName("formData_156");
            entity.Property(e => e.FormData157).HasColumnName("formData_157");
            entity.Property(e => e.FormData158).HasColumnName("formData_158");
            entity.Property(e => e.FormData159).HasColumnName("formData_159");
            entity.Property(e => e.FormData16).HasColumnName("formData_16");
            entity.Property(e => e.FormData160).HasColumnName("formData_160");
            entity.Property(e => e.FormData161).HasColumnName("formData_161");
            entity.Property(e => e.FormData162).HasColumnName("formData_162");
            entity.Property(e => e.FormData163).HasColumnName("formData_163");
            entity.Property(e => e.FormData164).HasColumnName("formData_164");
            entity.Property(e => e.FormData165).HasColumnName("formData_165");
            entity.Property(e => e.FormData166).HasColumnName("formData_166");
            entity.Property(e => e.FormData167).HasColumnName("formData_167");
            entity.Property(e => e.FormData168).HasColumnName("formData_168");
            entity.Property(e => e.FormData169).HasColumnName("formData_169");
            entity.Property(e => e.FormData17).HasColumnName("formData_17");
            entity.Property(e => e.FormData170).HasColumnName("formData_170");
            entity.Property(e => e.FormData171).HasColumnName("formData_171");
            entity.Property(e => e.FormData172).HasColumnName("formData_172");
            entity.Property(e => e.FormData173).HasColumnName("formData_173");
            entity.Property(e => e.FormData174).HasColumnName("formData_174");
            entity.Property(e => e.FormData175).HasColumnName("formData_175");
            entity.Property(e => e.FormData176).HasColumnName("formData_176");
            entity.Property(e => e.FormData177).HasColumnName("formData_177");
            entity.Property(e => e.FormData178).HasColumnName("formData_178");
            entity.Property(e => e.FormData179).HasColumnName("formData_179");
            entity.Property(e => e.FormData18).HasColumnName("formData_18");
            entity.Property(e => e.FormData180).HasColumnName("formData_180");
            entity.Property(e => e.FormData181).HasColumnName("formData_181");
            entity.Property(e => e.FormData182).HasColumnName("formData_182");
            entity.Property(e => e.FormData183).HasColumnName("formData_183");
            entity.Property(e => e.FormData184).HasColumnName("formData_184");
            entity.Property(e => e.FormData185).HasColumnName("formData_185");
            entity.Property(e => e.FormData186).HasColumnName("formData_186");
            entity.Property(e => e.FormData187).HasColumnName("formData_187");
            entity.Property(e => e.FormData188).HasColumnName("formData_188");
            entity.Property(e => e.FormData189).HasColumnName("formData_189");
            entity.Property(e => e.FormData19).HasColumnName("formData_19");
            entity.Property(e => e.FormData190).HasColumnName("formData_190");
            entity.Property(e => e.FormData191).HasColumnName("formData_191");
            entity.Property(e => e.FormData192).HasColumnName("formData_192");
            entity.Property(e => e.FormData193).HasColumnName("formData_193");
            entity.Property(e => e.FormData194).HasColumnName("formData_194");
            entity.Property(e => e.FormData195).HasColumnName("formData_195");
            entity.Property(e => e.FormData196).HasColumnName("formData_196");
            entity.Property(e => e.FormData197).HasColumnName("formData_197");
            entity.Property(e => e.FormData198).HasColumnName("formData_198");
            entity.Property(e => e.FormData199).HasColumnName("formData_199");
            entity.Property(e => e.FormData20).HasColumnName("formData_20");
            entity.Property(e => e.FormData200).HasColumnName("formData_200");
            entity.Property(e => e.FormData201).HasColumnName("formData_201");
            entity.Property(e => e.FormData202).HasColumnName("formData_202");
            entity.Property(e => e.FormData203).HasColumnName("formData_203");
            entity.Property(e => e.FormData204).HasColumnName("formData_204");
            entity.Property(e => e.FormData205).HasColumnName("formData_205");
            entity.Property(e => e.FormData206).HasColumnName("formData_206");
            entity.Property(e => e.FormData207).HasColumnName("formData_207");
            entity.Property(e => e.FormData208).HasColumnName("formData_208");
            entity.Property(e => e.FormData209).HasColumnName("formData_209");
            entity.Property(e => e.FormData21).HasColumnName("formData_21");
            entity.Property(e => e.FormData210).HasColumnName("formData_210");
            entity.Property(e => e.FormData211).HasColumnName("formData_211");
            entity.Property(e => e.FormData212).HasColumnName("formData_212");
            entity.Property(e => e.FormData213).HasColumnName("formData_213");
            entity.Property(e => e.FormData214).HasColumnName("formData_214");
            entity.Property(e => e.FormData215).HasColumnName("formData_215");
            entity.Property(e => e.FormData216).HasColumnName("formData_216");
            entity.Property(e => e.FormData217).HasColumnName("formData_217");
            entity.Property(e => e.FormData218).HasColumnName("formData_218");
            entity.Property(e => e.FormData219).HasColumnName("formData_219");
            entity.Property(e => e.FormData22).HasColumnName("formData_22");
            entity.Property(e => e.FormData220).HasColumnName("formData_220");
            entity.Property(e => e.FormData221).HasColumnName("formData_221");
            entity.Property(e => e.FormData222).HasColumnName("formData_222");
            entity.Property(e => e.FormData223).HasColumnName("formData_223");
            entity.Property(e => e.FormData224).HasColumnName("formData_224");
            entity.Property(e => e.FormData225).HasColumnName("formData_225");
            entity.Property(e => e.FormData226).HasColumnName("formData_226");
            entity.Property(e => e.FormData227).HasColumnName("formData_227");
            entity.Property(e => e.FormData228).HasColumnName("formData_228");
            entity.Property(e => e.FormData229).HasColumnName("formData_229");
            entity.Property(e => e.FormData23).HasColumnName("formData_23");
            entity.Property(e => e.FormData230).HasColumnName("formData_230");
            entity.Property(e => e.FormData231).HasColumnName("formData_231");
            entity.Property(e => e.FormData232).HasColumnName("formData_232");
            entity.Property(e => e.FormData233).HasColumnName("formData_233");
            entity.Property(e => e.FormData234).HasColumnName("formData_234");
            entity.Property(e => e.FormData235).HasColumnName("formData_235");
            entity.Property(e => e.FormData236).HasColumnName("formData_236");
            entity.Property(e => e.FormData237).HasColumnName("formData_237");
            entity.Property(e => e.FormData238).HasColumnName("formData_238");
            entity.Property(e => e.FormData239).HasColumnName("formData_239");
            entity.Property(e => e.FormData24).HasColumnName("formData_24");
            entity.Property(e => e.FormData240).HasColumnName("formData_240");
            entity.Property(e => e.FormData241).HasColumnName("formData_241");
            entity.Property(e => e.FormData242).HasColumnName("formData_242");
            entity.Property(e => e.FormData243).HasColumnName("formData_243");
            entity.Property(e => e.FormData244).HasColumnName("formData_244");
            entity.Property(e => e.FormData245).HasColumnName("formData_245");
            entity.Property(e => e.FormData246).HasColumnName("formData_246");
            entity.Property(e => e.FormData247).HasColumnName("formData_247");
            entity.Property(e => e.FormData248).HasColumnName("formData_248");
            entity.Property(e => e.FormData249).HasColumnName("formData_249");
            entity.Property(e => e.FormData25).HasColumnName("formData_25");
            entity.Property(e => e.FormData250).HasColumnName("formData_250");
            entity.Property(e => e.FormData26).HasColumnName("formData_26");
            entity.Property(e => e.FormData27).HasColumnName("formData_27");
            entity.Property(e => e.FormData28).HasColumnName("formData_28");
            entity.Property(e => e.FormData29).HasColumnName("formData_29");
            entity.Property(e => e.FormData30).HasColumnName("formData_30");
            entity.Property(e => e.FormData31).HasColumnName("formData_31");
            entity.Property(e => e.FormData32).HasColumnName("formData_32");
            entity.Property(e => e.FormData33).HasColumnName("formData_33");
            entity.Property(e => e.FormData34).HasColumnName("formData_34");
            entity.Property(e => e.FormData35).HasColumnName("formData_35");
            entity.Property(e => e.FormData36).HasColumnName("formData_36");
            entity.Property(e => e.FormData37).HasColumnName("formData_37");
            entity.Property(e => e.FormData38).HasColumnName("formData_38");
            entity.Property(e => e.FormData39).HasColumnName("formData_39");
            entity.Property(e => e.FormData40).HasColumnName("formData_40");
            entity.Property(e => e.FormData41).HasColumnName("formData_41");
            entity.Property(e => e.FormData42).HasColumnName("formData_42");
            entity.Property(e => e.FormData43).HasColumnName("formData_43");
            entity.Property(e => e.FormData44).HasColumnName("formData_44");
            entity.Property(e => e.FormData45).HasColumnName("formData_45");
            entity.Property(e => e.FormData46).HasColumnName("formData_46");
            entity.Property(e => e.FormData47).HasColumnName("formData_47");
            entity.Property(e => e.FormData48).HasColumnName("formData_48");
            entity.Property(e => e.FormData49).HasColumnName("formData_49");
            entity.Property(e => e.FormData50).HasColumnName("formData_50");
            entity.Property(e => e.FormData51).HasColumnName("formData_51");
            entity.Property(e => e.FormData52).HasColumnName("formData_52");
            entity.Property(e => e.FormData53).HasColumnName("formData_53");
            entity.Property(e => e.FormData54).HasColumnName("formData_54");
            entity.Property(e => e.FormData55).HasColumnName("formData_55");
            entity.Property(e => e.FormData56).HasColumnName("formData_56");
            entity.Property(e => e.FormData57).HasColumnName("formData_57");
            entity.Property(e => e.FormData58).HasColumnName("formData_58");
            entity.Property(e => e.FormData59).HasColumnName("formData_59");
            entity.Property(e => e.FormData60).HasColumnName("formData_60");
            entity.Property(e => e.FormData61).HasColumnName("formData_61");
            entity.Property(e => e.FormData62).HasColumnName("formData_62");
            entity.Property(e => e.FormData63).HasColumnName("formData_63");
            entity.Property(e => e.FormData64).HasColumnName("formData_64");
            entity.Property(e => e.FormData65).HasColumnName("formData_65");
            entity.Property(e => e.FormData66).HasColumnName("formData_66");
            entity.Property(e => e.FormData67).HasColumnName("formData_67");
            entity.Property(e => e.FormData68).HasColumnName("formData_68");
            entity.Property(e => e.FormData69).HasColumnName("formData_69");
            entity.Property(e => e.FormData70).HasColumnName("formData_70");
            entity.Property(e => e.FormData71).HasColumnName("formData_71");
            entity.Property(e => e.FormData72).HasColumnName("formData_72");
            entity.Property(e => e.FormData73).HasColumnName("formData_73");
            entity.Property(e => e.FormData74).HasColumnName("formData_74");
            entity.Property(e => e.FormData75).HasColumnName("formData_75");
            entity.Property(e => e.FormData76).HasColumnName("formData_76");
            entity.Property(e => e.FormData77).HasColumnName("formData_77");
            entity.Property(e => e.FormData78).HasColumnName("formData_78");
            entity.Property(e => e.FormData79).HasColumnName("formData_79");
            entity.Property(e => e.FormData80).HasColumnName("formData_80");
            entity.Property(e => e.FormData81).HasColumnName("formData_81");
            entity.Property(e => e.FormData82).HasColumnName("formData_82");
            entity.Property(e => e.FormData83).HasColumnName("formData_83");
            entity.Property(e => e.FormData84).HasColumnName("formData_84");
            entity.Property(e => e.FormData85).HasColumnName("formData_85");
            entity.Property(e => e.FormData86).HasColumnName("formData_86");
            entity.Property(e => e.FormData87).HasColumnName("formData_87");
            entity.Property(e => e.FormData88).HasColumnName("formData_88");
            entity.Property(e => e.FormData89).HasColumnName("formData_89");
            entity.Property(e => e.FormData90).HasColumnName("formData_90");
            entity.Property(e => e.FormData91).HasColumnName("formData_91");
            entity.Property(e => e.FormData92).HasColumnName("formData_92");
            entity.Property(e => e.FormData93).HasColumnName("formData_93");
            entity.Property(e => e.FormData94).HasColumnName("formData_94");
            entity.Property(e => e.FormData95).HasColumnName("formData_95");
            entity.Property(e => e.FormData96).HasColumnName("formData_96");
            entity.Property(e => e.FormData97).HasColumnName("formData_97");
            entity.Property(e => e.FormData98).HasColumnName("formData_98");
            entity.Property(e => e.FormData99).HasColumnName("formData_99");
            entity.Property(e => e.IsApproval01).HasColumnName("is_approval_01");
            entity.Property(e => e.IsApproval02).HasColumnName("is_approval_02");
            entity.Property(e => e.IsApproval03).HasColumnName("is_approval_03");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
            entity.Property(e => e.SwIdentityId).HasColumnName("SW_identityId");
            entity.Property(e => e.Uuid).HasColumnName("uuid");

            entity.HasOne(d => d.SwIdentity).WithMany(p => p.SwForms)
                .HasForeignKey(d => d.SwIdentityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SW_identitySW_forms");
        });

        modelBuilder.Entity<SwFormsTableName>(entity =>
        {
            entity.ToTable("SW_forms_tableNames");

            entity.HasIndex(e => e.SwFormsId, "IX_FK_SW_formsSW_forms_tableNames");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
            entity.Property(e => e.SwFormsId).HasColumnName("SW_formsId");

            entity.HasOne(d => d.SwForms).WithMany(p => p.SwFormsTableNames)
                .HasForeignKey(d => d.SwFormsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SW_formsSW_forms_tableNames");
        });

        modelBuilder.Entity<SwIdentity>(entity =>
        {
            entity.ToTable("SW_identity");

            entity.Property(e => e.Desc).HasColumnName("desc");
            entity.Property(e => e.Header).HasColumnName("header");
            entity.Property(e => e.Logo).HasColumnName("logo");
            entity.Property(e => e.Media01)
                .IsRequired()
                .HasColumnName("media_01");
            entity.Property(e => e.Media02)
                .IsRequired()
                .HasColumnName("media_02");
            entity.Property(e => e.Media03)
                .IsRequired()
                .HasColumnName("media_03");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
            entity.Property(e => e.Signature).HasColumnName("signature");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}