// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWIMS.Models;

public partial class SwSiteIdentity
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Desc { get; set; }

    public string Logo { get; set; }

    public string Media01 { get; set; }

    public string Media02 { get; set; }

    public string Media03 { get; set; }

    public string Header { get; set; }

    public string Signature { get; set; }

    public virtual ICollection<SwForm> SwForms { get; set; } = new List<SwForm>();
}