// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWIMS.Models;

#nullable disable

namespace SWIMS.Migrations
{
    [DbContext(typeof(SwimsDb_moreContext))]
    partial class SwimsDb_moreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWIMS.Models.SW_beneficiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("approved_amount")
                        .HasColumnType("float");

                    b.Property<string>("dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("martial_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middle_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telephone_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SW_beneficiary", (string)null);
                });

            modelBuilder.Entity("SWIMS.Models.SW_city", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SW_city", (string)null);
                });

            modelBuilder.Entity("SWIMS.Models.SW_financial_institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SW_financial_institution", (string)null);
                });

            modelBuilder.Entity("SWIMS.Models.SW_form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SW_identityId")
                        .HasColumnType("int");

                    b.Property<int?>("approvalAmt")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateModified")
                        .HasColumnType("datetime");

                    b.Property<string>("desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_linking")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uuid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SW_identityId" }, "IX_FK_SW_identitySW_forms");

                    b.ToTable("SW_forms");
                });

            modelBuilder.Entity("SWIMS.Models.SW_formProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SW_formsId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SW_formProcesses");
                });

            modelBuilder.Entity("SWIMS.Models.SW_formReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SW_formsId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SW_formsId" }, "IX_FK_SW_formsSW_formReport");

                    b.ToTable("SW_formReport", (string)null);
                });

            modelBuilder.Entity("SWIMS.Models.SW_formTableData_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SW_formsId")
                        .HasColumnType("int");

                    b.Property<string>("field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SW_formsId" }, "IX_FK_SW_formsSW_formTableData_Types");

                    b.ToTable("SW_formTableData_Types");
                });

            modelBuilder.Entity("SWIMS.Models.SW_formTableDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FormData01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData06")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData07")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData08")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData09")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData100")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData101")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData102")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData103")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData104")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData105")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData106")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData107")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData108")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData109")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData110")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData111")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData112")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData113")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData114")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData115")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData116")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData117")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData118")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData119")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData120")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData121")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData122")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData123")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData124")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData125")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData126")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData127")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData128")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData129")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData130")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData131")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData132")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData133")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData134")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData135")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData136")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData137")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData138")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData139")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData140")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData141")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData142")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData143")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData144")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData145")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData146")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData147")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData148")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData149")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData150")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData151")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData152")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData153")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData154")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData155")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData156")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData157")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData158")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData159")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData160")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData161")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData162")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData163")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData164")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData165")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData166")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData167")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData168")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData169")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData170")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData171")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData172")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData173")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData174")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData175")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData176")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData177")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData178")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData179")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData180")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData181")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData182")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData183")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData184")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData185")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData186")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData187")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData188")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData189")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData190")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData191")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData192")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData193")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData194")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData195")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData196")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData197")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData198")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData199")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData200")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData201")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData202")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData203")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData204")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData205")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData206")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData207")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData208")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData209")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData210")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData211")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData212")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData213")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData214")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData215")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData216")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData217")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData218")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData219")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData220")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData221")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData222")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData223")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData224")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData225")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData226")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData227")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData228")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData229")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData230")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData231")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData232")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData233")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData234")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData235")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData236")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData237")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData238")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData239")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData24")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData240")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData241")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData242")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData243")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData244")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData245")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData246")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData247")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData248")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData249")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData25")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData250")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData26")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData27")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData28")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData29")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData30")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData31")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData33")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData34")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData35")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData36")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData37")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData38")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData39")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData40")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData41")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData42")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData43")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData44")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData45")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData46")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData47")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData48")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData49")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData50")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData51")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData52")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData53")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData54")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData55")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData56")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData57")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData58")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData59")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData60")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData61")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData62")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData63")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData65")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData66")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData67")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData68")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData69")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData70")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData71")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData72")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData73")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData74")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData75")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData76")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData77")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData78")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData79")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData80")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData81")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData82")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData83")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData84")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData85")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData86")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData87")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData88")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData89")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData90")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData91")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData92")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData93")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData94")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData95")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData96")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData97")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData98")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormData99")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SW_formsId")
                        .HasColumnType("int");

                    b.Property<string>("isAppComment_01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isAppComment_02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isAppComment_03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("isApproval_01")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("isApproval_02")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("isApproval_03")
                        .HasColumnType("tinyint");

                    b.Property<string>("isApprover_01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isApprover_02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isApprover_03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("isLinkingForm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SW_formsId" }, "IX_FK_SW_formsSW_formTableData");

                    b.ToTable("SW_formTableData");
                });

            modelBuilder.Entity("SWIMS.Models.SW_formTableName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SW_formsId")
                        .HasColumnType("int");

                    b.Property<string>("field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SW_formsId" }, "IX_FK_SW_formsSW_formTableName");

                    b.ToTable("SW_formTableName", (string)null);
                });

            modelBuilder.Entity("SWIMS.Models.SW_identity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("media_01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("media_02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("media_03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("signature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SW_identity", (string)null);
                });

            modelBuilder.Entity("SWIMS.Models.SW_organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vendor_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SW_organization", (string)null);
                });

            modelBuilder.Entity("SWIMS.Models.SW_form", b =>
                {
                    b.HasOne("SWIMS.Models.SW_identity", "SW_identity")
                        .WithMany("SW_forms")
                        .HasForeignKey("SW_identityId")
                        .IsRequired()
                        .HasConstraintName("FK_SW_identitySW_forms");

                    b.Navigation("SW_identity");
                });

            modelBuilder.Entity("SWIMS.Models.SW_formReport", b =>
                {
                    b.HasOne("SWIMS.Models.SW_form", "SW_forms")
                        .WithMany("SW_formReports")
                        .HasForeignKey("SW_formsId")
                        .IsRequired()
                        .HasConstraintName("FK_SW_formsSW_formReport");

                    b.Navigation("SW_forms");
                });

            modelBuilder.Entity("SWIMS.Models.SW_formTableData_Type", b =>
                {
                    b.HasOne("SWIMS.Models.SW_form", "SW_forms")
                        .WithMany("SW_formTableData_Types")
                        .HasForeignKey("SW_formsId")
                        .IsRequired()
                        .HasConstraintName("FK_SW_formsSW_formTableData_Types");

                    b.Navigation("SW_forms");
                });

            modelBuilder.Entity("SWIMS.Models.SW_formTableDatum", b =>
                {
                    b.HasOne("SWIMS.Models.SW_form", "SW_forms")
                        .WithMany("SW_formTableData")
                        .HasForeignKey("SW_formsId")
                        .IsRequired()
                        .HasConstraintName("FK_SW_formsSW_formTableData");

                    b.Navigation("SW_forms");
                });

            modelBuilder.Entity("SWIMS.Models.SW_formTableName", b =>
                {
                    b.HasOne("SWIMS.Models.SW_form", "SW_forms")
                        .WithMany("SW_formTableNames")
                        .HasForeignKey("SW_formsId")
                        .IsRequired()
                        .HasConstraintName("FK_SW_formsSW_formTableName");

                    b.Navigation("SW_forms");
                });

            modelBuilder.Entity("SWIMS.Models.SW_form", b =>
                {
                    b.Navigation("SW_formReports");

                    b.Navigation("SW_formTableData");

                    b.Navigation("SW_formTableData_Types");

                    b.Navigation("SW_formTableNames");
                });

            modelBuilder.Entity("SWIMS.Models.SW_identity", b =>
                {
                    b.Navigation("SW_forms");
                });
#pragma warning restore 612, 618
        }
    }
}
