// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWIMS.Data.Lookups;

#nullable disable

namespace SWIMS.Migrations.Lookup
{
    [DbContext(typeof(SwimsLookupDbContext))]
    [Migration("20251222203841_Lookup_FormClassificationLinks")]
    partial class Lookup_FormClassificationLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ref")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWIMS.Models.Lookups.SW_formFormType", b =>
                {
                    b.Property<int>("SW_formsId")
                        .HasColumnType("int");

                    b.Property<int>("SW_formTypeId")
                        .HasColumnType("int");

                    b.HasKey("SW_formsId");

                    b.HasIndex("SW_formTypeId");

                    b.ToTable("SW_formFormType", "ref");
                });

            modelBuilder.Entity("SWIMS.Models.Lookups.SW_formProgramTag", b =>
                {
                    b.Property<int>("SW_formsId")
                        .HasColumnType("int");

                    b.Property<int>("SW_programTagId")
                        .HasColumnType("int");

                    b.HasKey("SW_formsId", "SW_programTagId");

                    b.HasIndex("SW_formsId");

                    b.HasIndex("SW_programTagId");

                    b.ToTable("SW_formProgramTag", "ref");
                });

            modelBuilder.Entity("SWIMS.Models.SW_formType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("SW_formType", "ref");
                });

            modelBuilder.Entity("SWIMS.Models.SW_programTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("SW_programTag", "ref");
                });

            modelBuilder.Entity("SWIMS.Models.Lookups.SW_formFormType", b =>
                {
                    b.HasOne("SWIMS.Models.SW_formType", "SW_formType")
                        .WithMany()
                        .HasForeignKey("SW_formTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SW_formType");
                });

            modelBuilder.Entity("SWIMS.Models.Lookups.SW_formProgramTag", b =>
                {
                    b.HasOne("SWIMS.Models.SW_programTag", "SW_programTag")
                        .WithMany()
                        .HasForeignKey("SW_programTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SW_programTag");
                });
#pragma warning restore 612, 618
        }
    }
}
