//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class endpoint_policy_assignments
    {
        public int Id { get; set; }
        public string MatchType { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Page { get; set; }
        public string Path { get; set; }
        public string Regex { get; set; }
        public string Notes { get; set; }
        public int PolicyId { get; set; }
        public string PolicyName { get; set; }
        public bool IsEnabled { get; set; }
        public int Priority { get; set; }
        public System.DateTimeOffset UpdatedAt { get; set; }
    
        public virtual policy policy { get; set; }
    }
}
