//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class policy_roles
    {
        public int Id { get; set; }
        public int AuthorizationPolicyEntityId { get; set; }
        public int RoleId { get; set; }
        public string RoleName { get; set; }
    
        public virtual policy policy { get; set; }
        public virtual role role { get; set; }
    }
}
