//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class stored_processes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stored_processes()
        {
            this.stored_process_params = new HashSet<stored_process_params>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ConnectionKey { get; set; }
        public string DataSource { get; set; }
        public string Database { get; set; }
        public string DbUserEncrypted { get; set; }
        public string DbPasswordEncrypted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stored_process_params> stored_process_params { get; set; }
    }
}
