
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model_Designer
{

using System;
    using System.Collections.Generic;
    
public partial class SW_beneficiary
{

    public int Id { get; set; }

    public string uuid { get; set; }

    public string first_name { get; set; }

    public string middle_name { get; set; }

    public string last_name { get; set; }

    public string dob { get; set; }

    public string gender { get; set; }

    public string martial_status { get; set; }

    public string id_number { get; set; }

    public string telephone_number { get; set; }

    public string status { get; set; }

    public Nullable<double> approved_amount { get; set; }

}

}
