//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SW_forms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SW_forms()
        {
            this.SW_formTableName = new HashSet<SW_formTableName>();
            this.SW_formTableData = new HashSet<SW_formTableData>();
            this.SW_formTableData_Types = new HashSet<SW_formTableData_Types>();
        }
    
        public int Id { get; set; }
        public Nullable<int> uuid { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string form { get; set; }
        public Nullable<byte> isApproval_01 { get; set; }
        public Nullable<byte> isApproval_02 { get; set; }
        public Nullable<byte> isApproval_03 { get; set; }
        public System.DateTime dateModified { get; set; }
        public int SW_identityId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SW_formTableName> SW_formTableName { get; set; }
        public virtual SW_identity SW_identity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SW_formTableData> SW_formTableData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SW_formTableData_Types> SW_formTableData_Types { get; set; }
    }
}
