//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SW_forms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SW_forms()
        {
            this.SW_forms_tableNames = new HashSet<SW_forms_tableNames>();
        }
    
        public int Id { get; set; }
        public Nullable<int> uuid { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string form { get; set; }
        public Nullable<byte> is_approval_01 { get; set; }
        public Nullable<byte> is_approval_02 { get; set; }
        public Nullable<byte> is_approval_03 { get; set; }
        public System.DateTime dateModified { get; set; }
        public int SW_identityId { get; set; }
        public string formData_01 { get; set; }
        public string formData_02 { get; set; }
        public string formData_03 { get; set; }
        public string formData_04 { get; set; }
        public string formData_05 { get; set; }
        public string formData_06 { get; set; }
        public string formData_07 { get; set; }
        public string formData_08 { get; set; }
        public string formData_09 { get; set; }
        public string formData_10 { get; set; }
        public string formData_11 { get; set; }
        public string formData_12 { get; set; }
        public string formData_13 { get; set; }
        public string formData_14 { get; set; }
        public string formData_15 { get; set; }
        public string formData_16 { get; set; }
        public string formData_17 { get; set; }
        public string formData_18 { get; set; }
        public string formData_19 { get; set; }
        public string formData_20 { get; set; }
        public string formData_21 { get; set; }
        public string formData_22 { get; set; }
        public string formData_23 { get; set; }
        public string formData_24 { get; set; }
        public string formData_25 { get; set; }
        public string formData_26 { get; set; }
        public string formData_27 { get; set; }
        public string formData_28 { get; set; }
        public string formData_29 { get; set; }
        public string formData_30 { get; set; }
        public string formData_31 { get; set; }
        public string formData_32 { get; set; }
        public string formData_33 { get; set; }
        public string formData_34 { get; set; }
        public string formData_35 { get; set; }
        public string formData_36 { get; set; }
        public string formData_37 { get; set; }
        public string formData_38 { get; set; }
        public string formData_39 { get; set; }
        public string formData_40 { get; set; }
        public string formData_41 { get; set; }
        public string formData_42 { get; set; }
        public string formData_43 { get; set; }
        public string formData_44 { get; set; }
        public string formData_45 { get; set; }
        public string formData_46 { get; set; }
        public string formData_47 { get; set; }
        public string formData_48 { get; set; }
        public string formData_49 { get; set; }
        public string formData_50 { get; set; }
        public string formData_51 { get; set; }
        public string formData_52 { get; set; }
        public string formData_53 { get; set; }
        public string formData_54 { get; set; }
        public string formData_55 { get; set; }
        public string formData_56 { get; set; }
        public string formData_57 { get; set; }
        public string formData_58 { get; set; }
        public string formData_59 { get; set; }
        public string formData_60 { get; set; }
        public string formData_61 { get; set; }
        public string formData_62 { get; set; }
        public string formData_63 { get; set; }
        public string formData_64 { get; set; }
        public string formData_65 { get; set; }
        public string formData_66 { get; set; }
        public string formData_67 { get; set; }
        public string formData_68 { get; set; }
        public string formData_69 { get; set; }
        public string formData_70 { get; set; }
        public string formData_71 { get; set; }
        public string formData_72 { get; set; }
        public string formData_73 { get; set; }
        public string formData_74 { get; set; }
        public string formData_75 { get; set; }
        public string formData_76 { get; set; }
        public string formData_77 { get; set; }
        public string formData_78 { get; set; }
        public string formData_79 { get; set; }
        public string formData_80 { get; set; }
        public string formData_81 { get; set; }
        public string formData_82 { get; set; }
        public string formData_83 { get; set; }
        public string formData_84 { get; set; }
        public string formData_85 { get; set; }
        public string formData_86 { get; set; }
        public string formData_87 { get; set; }
        public string formData_88 { get; set; }
        public string formData_89 { get; set; }
        public string formData_90 { get; set; }
        public string formData_91 { get; set; }
        public string formData_92 { get; set; }
        public string formData_93 { get; set; }
        public string formData_94 { get; set; }
        public string formData_95 { get; set; }
        public string formData_96 { get; set; }
        public string formData_97 { get; set; }
        public string formData_98 { get; set; }
        public string formData_99 { get; set; }
        public string formData_100 { get; set; }
        public string formData_101 { get; set; }
        public string formData_102 { get; set; }
        public string formData_103 { get; set; }
        public string formData_104 { get; set; }
        public string formData_105 { get; set; }
        public string formData_106 { get; set; }
        public string formData_107 { get; set; }
        public string formData_108 { get; set; }
        public string formData_109 { get; set; }
        public string formData_110 { get; set; }
        public string formData_111 { get; set; }
        public string formData_112 { get; set; }
        public string formData_113 { get; set; }
        public string formData_114 { get; set; }
        public string formData_115 { get; set; }
        public string formData_116 { get; set; }
        public string formData_117 { get; set; }
        public string formData_118 { get; set; }
        public string formData_119 { get; set; }
        public string formData_120 { get; set; }
        public string formData_121 { get; set; }
        public string formData_122 { get; set; }
        public string formData_123 { get; set; }
        public string formData_124 { get; set; }
        public string formData_125 { get; set; }
        public string formData_126 { get; set; }
        public string formData_127 { get; set; }
        public string formData_128 { get; set; }
        public string formData_129 { get; set; }
        public string formData_130 { get; set; }
        public string formData_131 { get; set; }
        public string formData_132 { get; set; }
        public string formData_133 { get; set; }
        public string formData_134 { get; set; }
        public string formData_135 { get; set; }
        public string formData_136 { get; set; }
        public string formData_137 { get; set; }
        public string formData_138 { get; set; }
        public string formData_139 { get; set; }
        public string formData_140 { get; set; }
        public string formData_141 { get; set; }
        public string formData_142 { get; set; }
        public string formData_143 { get; set; }
        public string formData_144 { get; set; }
        public string formData_145 { get; set; }
        public string formData_146 { get; set; }
        public string formData_147 { get; set; }
        public string formData_148 { get; set; }
        public string formData_149 { get; set; }
        public string formData_150 { get; set; }
        public string formData_151 { get; set; }
        public string formData_152 { get; set; }
        public string formData_153 { get; set; }
        public string formData_154 { get; set; }
        public string formData_155 { get; set; }
        public string formData_156 { get; set; }
        public string formData_157 { get; set; }
        public string formData_158 { get; set; }
        public string formData_159 { get; set; }
        public string formData_160 { get; set; }
        public string formData_161 { get; set; }
        public string formData_162 { get; set; }
        public string formData_163 { get; set; }
        public string formData_164 { get; set; }
        public string formData_165 { get; set; }
        public string formData_166 { get; set; }
        public string formData_167 { get; set; }
        public string formData_168 { get; set; }
        public string formData_169 { get; set; }
        public string formData_170 { get; set; }
        public string formData_171 { get; set; }
        public string formData_172 { get; set; }
        public string formData_173 { get; set; }
        public string formData_174 { get; set; }
        public string formData_175 { get; set; }
        public string formData_176 { get; set; }
        public string formData_177 { get; set; }
        public string formData_178 { get; set; }
        public string formData_179 { get; set; }
        public string formData_180 { get; set; }
        public string formData_181 { get; set; }
        public string formData_182 { get; set; }
        public string formData_183 { get; set; }
        public string formData_184 { get; set; }
        public string formData_185 { get; set; }
        public string formData_186 { get; set; }
        public string formData_187 { get; set; }
        public string formData_188 { get; set; }
        public string formData_189 { get; set; }
        public string formData_190 { get; set; }
        public string formData_191 { get; set; }
        public string formData_192 { get; set; }
        public string formData_193 { get; set; }
        public string formData_194 { get; set; }
        public string formData_195 { get; set; }
        public string formData_196 { get; set; }
        public string formData_197 { get; set; }
        public string formData_198 { get; set; }
        public string formData_199 { get; set; }
        public string formData_200 { get; set; }
        public string formData_201 { get; set; }
        public string formData_202 { get; set; }
        public string formData_203 { get; set; }
        public string formData_204 { get; set; }
        public string formData_205 { get; set; }
        public string formData_206 { get; set; }
        public string formData_207 { get; set; }
        public string formData_208 { get; set; }
        public string formData_209 { get; set; }
        public string formData_210 { get; set; }
        public string formData_211 { get; set; }
        public string formData_212 { get; set; }
        public string formData_213 { get; set; }
        public string formData_214 { get; set; }
        public string formData_215 { get; set; }
        public string formData_216 { get; set; }
        public string formData_217 { get; set; }
        public string formData_218 { get; set; }
        public string formData_219 { get; set; }
        public string formData_220 { get; set; }
        public string formData_221 { get; set; }
        public string formData_222 { get; set; }
        public string formData_223 { get; set; }
        public string formData_224 { get; set; }
        public string formData_225 { get; set; }
        public string formData_226 { get; set; }
        public string formData_227 { get; set; }
        public string formData_228 { get; set; }
        public string formData_229 { get; set; }
        public string formData_230 { get; set; }
        public string formData_231 { get; set; }
        public string formData_232 { get; set; }
        public string formData_233 { get; set; }
        public string formData_234 { get; set; }
        public string formData_235 { get; set; }
        public string formData_236 { get; set; }
        public string formData_237 { get; set; }
        public string formData_238 { get; set; }
        public string formData_239 { get; set; }
        public string formData_240 { get; set; }
        public string formData_241 { get; set; }
        public string formData_242 { get; set; }
        public string formData_243 { get; set; }
        public string formData_244 { get; set; }
        public string formData_245 { get; set; }
        public string formData_246 { get; set; }
        public string formData_247 { get; set; }
        public string formData_248 { get; set; }
        public string formData_249 { get; set; }
        public string formData_250 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SW_forms_tableNames> SW_forms_tableNames { get; set; }
        public virtual SW_identity SW_identity { get; set; }
    }
}
