
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model_Designer
{

using System;
    using System.Collections.Generic;
    
public partial class SW_identity
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SW_identity()
    {

        this.SW_forms = new HashSet<SW_forms>();

    }


    public int Id { get; set; }

    public string name { get; set; }

    public string desc { get; set; }

    public string logo { get; set; }

    public string media_01 { get; set; }

    public string media_02 { get; set; }

    public string media_03 { get; set; }

    public string header { get; set; }

    public string signature { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SW_forms> SW_forms { get; set; }

}

}
