
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model_Designer
{

using System;
    using System.Collections.Generic;
    
public partial class SW_organization
{

    public int Id { get; set; }

    public string vendor_id { get; set; }

    public string name { get; set; }

    public string type { get; set; }

    public string active { get; set; }

}

}
