
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model_Designer
{

using System;
    using System.Collections.Generic;
    
public partial class SW_roles
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SW_roles()
    {

        this.SW_users = new HashSet<SW_users>();

        this.SW_role_claims = new HashSet<SW_role_claims>();

        this.SW_users1 = new HashSet<SW_users>();

    }


    public int Id { get; set; }

    public string name { get; set; }

    public string NormalizedName { get; set; }

    public string ConcurrencyStamp { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SW_users> SW_users { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SW_role_claims> SW_role_claims { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SW_users> SW_users1 { get; set; }

}

}
