
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model_Designer
{

using System;
    using System.Collections.Generic;
    
public partial class SW_role_claims
{

    public int Id { get; set; }

    public int RoleId { get; set; }

    public string ClaimType { get; set; }

    public string ClaimValue { get; set; }



    public virtual SW_roles SW_roles { get; set; }

}

}
