// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWIMS.Data.Cases;

#nullable disable

namespace SWIMS.Migrations.Cases
{
    [DbContext(typeof(SwimsCasesDbContext))]
    [Migration("20260112180204_Cases_AddBenefitPeriodFields")]
    partial class Cases_AddBenefitPeriodFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("case")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWIMS.Models.SW_case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProgramTagId")
                        .HasColumnType("int");

                    b.Property<int>("SW_beneficiaryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("benefit_end_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("benefit_end_at_override")
                        .HasColumnType("datetime2");

                    b.Property<int?>("benefit_period_months")
                        .HasColumnType("int");

                    b.Property<int?>("benefit_period_months_override")
                        .HasColumnType("int");

                    b.Property<string>("benefit_period_source")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("benefit_start_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("benefit_start_at_override")
                        .HasColumnType("datetime2");

                    b.Property<string>("case_number")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("closed_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("program_tag")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("SW_case", "case");
                });

            modelBuilder.Entity("SWIMS.Models.SW_caseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SW_caseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("assigned_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("role_on_case")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("unassigned_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SW_caseId");

                    b.ToTable("SW_caseAssignment", "case");
                });

            modelBuilder.Entity("SWIMS.Models.SW_caseForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SW_caseId")
                        .HasColumnType("int");

                    b.Property<int>("SW_formTableDatumId")
                        .HasColumnType("int");

                    b.Property<string>("form_role")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("is_primary_application")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("linked_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("linked_by")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("SW_caseId");

                    b.ToTable("SW_caseForm", "case");
                });

            modelBuilder.Entity("SWIMS.Models.SW_caseAssignment", b =>
                {
                    b.HasOne("SWIMS.Models.SW_case", "SW_case")
                        .WithMany("SW_caseAssignments")
                        .HasForeignKey("SW_caseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SW_case");
                });

            modelBuilder.Entity("SWIMS.Models.SW_caseForm", b =>
                {
                    b.HasOne("SWIMS.Models.SW_case", "SW_case")
                        .WithMany("SW_caseForms")
                        .HasForeignKey("SW_caseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SW_case");
                });

            modelBuilder.Entity("SWIMS.Models.SW_case", b =>
                {
                    b.Navigation("SW_caseAssignments");

                    b.Navigation("SW_caseForms");
                });
#pragma warning restore 612, 618
        }
    }
}
