// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWIMS.Models;

#nullable disable

namespace SWIMS.Migrations.SwimsMore
{
    [DbContext(typeof(SwimsDb_moreContext))]
    partial class SwimsDb_moreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWIMS.Models.SwForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime")
                        .HasColumnName("dateModified");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("desc");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("form");

                    b.Property<string>("FormData01")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_01");

                    b.Property<string>("FormData02")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_02");

                    b.Property<string>("FormData03")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_03");

                    b.Property<string>("FormData04")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_04");

                    b.Property<string>("FormData05")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_05");

                    b.Property<string>("FormData06")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_06");

                    b.Property<string>("FormData07")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_07");

                    b.Property<string>("FormData08")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_08");

                    b.Property<string>("FormData09")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_09");

                    b.Property<string>("FormData10")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_10");

                    b.Property<string>("FormData100")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_100");

                    b.Property<string>("FormData101")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_101");

                    b.Property<string>("FormData102")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_102");

                    b.Property<string>("FormData103")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_103");

                    b.Property<string>("FormData104")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_104");

                    b.Property<string>("FormData105")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_105");

                    b.Property<string>("FormData106")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_106");

                    b.Property<string>("FormData107")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_107");

                    b.Property<string>("FormData108")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_108");

                    b.Property<string>("FormData109")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_109");

                    b.Property<string>("FormData11")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_11");

                    b.Property<string>("FormData110")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_110");

                    b.Property<string>("FormData111")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_111");

                    b.Property<string>("FormData112")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_112");

                    b.Property<string>("FormData113")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_113");

                    b.Property<string>("FormData114")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_114");

                    b.Property<string>("FormData115")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_115");

                    b.Property<string>("FormData116")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_116");

                    b.Property<string>("FormData117")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_117");

                    b.Property<string>("FormData118")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_118");

                    b.Property<string>("FormData119")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_119");

                    b.Property<string>("FormData12")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_12");

                    b.Property<string>("FormData120")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_120");

                    b.Property<string>("FormData121")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_121");

                    b.Property<string>("FormData122")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_122");

                    b.Property<string>("FormData123")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_123");

                    b.Property<string>("FormData124")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_124");

                    b.Property<string>("FormData125")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_125");

                    b.Property<string>("FormData126")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_126");

                    b.Property<string>("FormData127")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_127");

                    b.Property<string>("FormData128")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_128");

                    b.Property<string>("FormData129")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_129");

                    b.Property<string>("FormData13")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_13");

                    b.Property<string>("FormData130")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_130");

                    b.Property<string>("FormData131")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_131");

                    b.Property<string>("FormData132")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_132");

                    b.Property<string>("FormData133")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_133");

                    b.Property<string>("FormData134")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_134");

                    b.Property<string>("FormData135")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_135");

                    b.Property<string>("FormData136")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_136");

                    b.Property<string>("FormData137")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_137");

                    b.Property<string>("FormData138")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_138");

                    b.Property<string>("FormData139")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_139");

                    b.Property<string>("FormData14")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_14");

                    b.Property<string>("FormData140")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_140");

                    b.Property<string>("FormData141")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_141");

                    b.Property<string>("FormData142")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_142");

                    b.Property<string>("FormData143")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_143");

                    b.Property<string>("FormData144")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_144");

                    b.Property<string>("FormData145")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_145");

                    b.Property<string>("FormData146")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_146");

                    b.Property<string>("FormData147")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_147");

                    b.Property<string>("FormData148")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_148");

                    b.Property<string>("FormData149")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_149");

                    b.Property<string>("FormData15")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_15");

                    b.Property<string>("FormData150")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_150");

                    b.Property<string>("FormData151")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_151");

                    b.Property<string>("FormData152")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_152");

                    b.Property<string>("FormData153")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_153");

                    b.Property<string>("FormData154")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_154");

                    b.Property<string>("FormData155")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_155");

                    b.Property<string>("FormData156")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_156");

                    b.Property<string>("FormData157")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_157");

                    b.Property<string>("FormData158")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_158");

                    b.Property<string>("FormData159")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_159");

                    b.Property<string>("FormData16")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_16");

                    b.Property<string>("FormData160")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_160");

                    b.Property<string>("FormData161")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_161");

                    b.Property<string>("FormData162")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_162");

                    b.Property<string>("FormData163")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_163");

                    b.Property<string>("FormData164")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_164");

                    b.Property<string>("FormData165")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_165");

                    b.Property<string>("FormData166")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_166");

                    b.Property<string>("FormData167")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_167");

                    b.Property<string>("FormData168")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_168");

                    b.Property<string>("FormData169")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_169");

                    b.Property<string>("FormData17")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_17");

                    b.Property<string>("FormData170")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_170");

                    b.Property<string>("FormData171")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_171");

                    b.Property<string>("FormData172")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_172");

                    b.Property<string>("FormData173")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_173");

                    b.Property<string>("FormData174")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_174");

                    b.Property<string>("FormData175")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_175");

                    b.Property<string>("FormData176")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_176");

                    b.Property<string>("FormData177")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_177");

                    b.Property<string>("FormData178")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_178");

                    b.Property<string>("FormData179")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_179");

                    b.Property<string>("FormData18")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_18");

                    b.Property<string>("FormData180")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_180");

                    b.Property<string>("FormData181")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_181");

                    b.Property<string>("FormData182")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_182");

                    b.Property<string>("FormData183")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_183");

                    b.Property<string>("FormData184")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_184");

                    b.Property<string>("FormData185")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_185");

                    b.Property<string>("FormData186")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_186");

                    b.Property<string>("FormData187")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_187");

                    b.Property<string>("FormData188")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_188");

                    b.Property<string>("FormData189")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_189");

                    b.Property<string>("FormData19")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_19");

                    b.Property<string>("FormData190")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_190");

                    b.Property<string>("FormData191")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_191");

                    b.Property<string>("FormData192")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_192");

                    b.Property<string>("FormData193")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_193");

                    b.Property<string>("FormData194")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_194");

                    b.Property<string>("FormData195")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_195");

                    b.Property<string>("FormData196")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_196");

                    b.Property<string>("FormData197")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_197");

                    b.Property<string>("FormData198")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_198");

                    b.Property<string>("FormData199")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_199");

                    b.Property<string>("FormData20")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_20");

                    b.Property<string>("FormData200")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_200");

                    b.Property<string>("FormData201")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_201");

                    b.Property<string>("FormData202")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_202");

                    b.Property<string>("FormData203")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_203");

                    b.Property<string>("FormData204")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_204");

                    b.Property<string>("FormData205")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_205");

                    b.Property<string>("FormData206")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_206");

                    b.Property<string>("FormData207")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_207");

                    b.Property<string>("FormData208")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_208");

                    b.Property<string>("FormData209")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_209");

                    b.Property<string>("FormData21")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_21");

                    b.Property<string>("FormData210")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_210");

                    b.Property<string>("FormData211")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_211");

                    b.Property<string>("FormData212")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_212");

                    b.Property<string>("FormData213")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_213");

                    b.Property<string>("FormData214")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_214");

                    b.Property<string>("FormData215")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_215");

                    b.Property<string>("FormData216")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_216");

                    b.Property<string>("FormData217")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_217");

                    b.Property<string>("FormData218")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_218");

                    b.Property<string>("FormData219")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_219");

                    b.Property<string>("FormData22")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_22");

                    b.Property<string>("FormData220")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_220");

                    b.Property<string>("FormData221")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_221");

                    b.Property<string>("FormData222")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_222");

                    b.Property<string>("FormData223")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_223");

                    b.Property<string>("FormData224")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_224");

                    b.Property<string>("FormData225")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_225");

                    b.Property<string>("FormData226")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_226");

                    b.Property<string>("FormData227")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_227");

                    b.Property<string>("FormData228")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_228");

                    b.Property<string>("FormData229")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_229");

                    b.Property<string>("FormData23")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_23");

                    b.Property<string>("FormData230")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_230");

                    b.Property<string>("FormData231")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_231");

                    b.Property<string>("FormData232")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_232");

                    b.Property<string>("FormData233")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_233");

                    b.Property<string>("FormData234")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_234");

                    b.Property<string>("FormData235")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_235");

                    b.Property<string>("FormData236")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_236");

                    b.Property<string>("FormData237")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_237");

                    b.Property<string>("FormData238")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_238");

                    b.Property<string>("FormData239")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_239");

                    b.Property<string>("FormData24")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_24");

                    b.Property<string>("FormData240")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_240");

                    b.Property<string>("FormData241")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_241");

                    b.Property<string>("FormData242")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_242");

                    b.Property<string>("FormData243")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_243");

                    b.Property<string>("FormData244")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_244");

                    b.Property<string>("FormData245")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_245");

                    b.Property<string>("FormData246")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_246");

                    b.Property<string>("FormData247")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_247");

                    b.Property<string>("FormData248")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_248");

                    b.Property<string>("FormData249")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_249");

                    b.Property<string>("FormData25")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_25");

                    b.Property<string>("FormData250")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_250");

                    b.Property<string>("FormData26")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_26");

                    b.Property<string>("FormData27")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_27");

                    b.Property<string>("FormData28")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_28");

                    b.Property<string>("FormData29")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_29");

                    b.Property<string>("FormData30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_30");

                    b.Property<string>("FormData31")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_31");

                    b.Property<string>("FormData32")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_32");

                    b.Property<string>("FormData33")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_33");

                    b.Property<string>("FormData34")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_34");

                    b.Property<string>("FormData35")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_35");

                    b.Property<string>("FormData36")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_36");

                    b.Property<string>("FormData37")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_37");

                    b.Property<string>("FormData38")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_38");

                    b.Property<string>("FormData39")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_39");

                    b.Property<string>("FormData40")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_40");

                    b.Property<string>("FormData41")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_41");

                    b.Property<string>("FormData42")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_42");

                    b.Property<string>("FormData43")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_43");

                    b.Property<string>("FormData44")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_44");

                    b.Property<string>("FormData45")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_45");

                    b.Property<string>("FormData46")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_46");

                    b.Property<string>("FormData47")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_47");

                    b.Property<string>("FormData48")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_48");

                    b.Property<string>("FormData49")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_49");

                    b.Property<string>("FormData50")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_50");

                    b.Property<string>("FormData51")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_51");

                    b.Property<string>("FormData52")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_52");

                    b.Property<string>("FormData53")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_53");

                    b.Property<string>("FormData54")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_54");

                    b.Property<string>("FormData55")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_55");

                    b.Property<string>("FormData56")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_56");

                    b.Property<string>("FormData57")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_57");

                    b.Property<string>("FormData58")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_58");

                    b.Property<string>("FormData59")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_59");

                    b.Property<string>("FormData60")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_60");

                    b.Property<string>("FormData61")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_61");

                    b.Property<string>("FormData62")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_62");

                    b.Property<string>("FormData63")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_63");

                    b.Property<string>("FormData64")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_64");

                    b.Property<string>("FormData65")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_65");

                    b.Property<string>("FormData66")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_66");

                    b.Property<string>("FormData67")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_67");

                    b.Property<string>("FormData68")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_68");

                    b.Property<string>("FormData69")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_69");

                    b.Property<string>("FormData70")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_70");

                    b.Property<string>("FormData71")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_71");

                    b.Property<string>("FormData72")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_72");

                    b.Property<string>("FormData73")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_73");

                    b.Property<string>("FormData74")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_74");

                    b.Property<string>("FormData75")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_75");

                    b.Property<string>("FormData76")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_76");

                    b.Property<string>("FormData77")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_77");

                    b.Property<string>("FormData78")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_78");

                    b.Property<string>("FormData79")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_79");

                    b.Property<string>("FormData80")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_80");

                    b.Property<string>("FormData81")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_81");

                    b.Property<string>("FormData82")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_82");

                    b.Property<string>("FormData83")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_83");

                    b.Property<string>("FormData84")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_84");

                    b.Property<string>("FormData85")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_85");

                    b.Property<string>("FormData86")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_86");

                    b.Property<string>("FormData87")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_87");

                    b.Property<string>("FormData88")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_88");

                    b.Property<string>("FormData89")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_89");

                    b.Property<string>("FormData90")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_90");

                    b.Property<string>("FormData91")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_91");

                    b.Property<string>("FormData92")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_92");

                    b.Property<string>("FormData93")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_93");

                    b.Property<string>("FormData94")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_94");

                    b.Property<string>("FormData95")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_95");

                    b.Property<string>("FormData96")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_96");

                    b.Property<string>("FormData97")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_97");

                    b.Property<string>("FormData98")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_98");

                    b.Property<string>("FormData99")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formData_99");

                    b.Property<byte?>("IsApproval01")
                        .HasColumnType("tinyint")
                        .HasColumnName("is_approval_01");

                    b.Property<byte?>("IsApproval02")
                        .HasColumnType("tinyint")
                        .HasColumnName("is_approval_02");

                    b.Property<byte?>("IsApproval03")
                        .HasColumnType("tinyint")
                        .HasColumnName("is_approval_03");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("SwIdentityId")
                        .HasColumnType("int")
                        .HasColumnName("SW_identityId");

                    b.Property<int?>("Uuid")
                        .HasColumnType("int")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SwIdentityId" }, "IX_FK_SW_identitySW_forms");

                    b.ToTable("SW_forms", (string)null);
                });

            modelBuilder.Entity("SWIMS.Models.SwFormsTableName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("SwFormsId")
                        .HasColumnType("int")
                        .HasColumnName("SW_formsId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SwFormsId" }, "IX_FK_SW_formsSW_forms_tableNames");

                    b.ToTable("SW_forms_tableNames", (string)null);
                });

            modelBuilder.Entity("SWIMS.Models.SW_identity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("desc");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("header");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logo");

                    b.Property<string>("Media01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("media_01");

                    b.Property<string>("Media02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("media_02");

                    b.Property<string>("Media03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("media_03");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("signature");

                    b.HasKey("Id");

                    b.ToTable("SW_identity", (string)null);
                });

            modelBuilder.Entity("SWIMS.Models.SwForm", b =>
                {
                    b.HasOne("SWIMS.Models.SW_identity", "SwIdentity")
                        .WithMany("SwForms")
                        .HasForeignKey("SwIdentityId")
                        .IsRequired()
                        .HasConstraintName("FK_SW_identitySW_forms");

                    b.Navigation("SwIdentity");
                });

            modelBuilder.Entity("SWIMS.Models.SwFormsTableName", b =>
                {
                    b.HasOne("SWIMS.Models.SwForm", "SwForms")
                        .WithMany("SwFormsTableNames")
                        .HasForeignKey("SwFormsId")
                        .IsRequired()
                        .HasConstraintName("FK_SW_formsSW_forms_tableNames");

                    b.Navigation("SwForms");
                });

            modelBuilder.Entity("SWIMS.Models.SwForm", b =>
                {
                    b.Navigation("SwFormsTableNames");
                });

            modelBuilder.Entity("SWIMS.Models.SW_identity", b =>
                {
                    b.Navigation("SwForms");
                });
#pragma warning restore 612, 618
        }
    }
}
